### ISSUE TITLE
Component previews do not show largest breakpoint component behaviour

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-design-system#348] opened 2023-02-13 08:08 UTC
## Summary of the bug
Whilst testing on the guidance site it seems that the app title in top navigation breaks up at different breakpoints, but it seems like it isn't necessary.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to design.sis.gov.uk
2. Click on Components > Top Nav
3. Change screen size slowly
4. See ICDS be split into 
I
C
D
S

## 🧐 Expected behaviour
This should not break up.

## 📸 Screenshots or code
<img width="704" alt="Screenshot 2023-02-13 at 08 03 39" src="https://user-images.githubusercontent.com/111882034/218403470-2c3e3f97-02d8-45db-a253-d92cd8e78c69.png">
<img width="662" alt="Screenshot 2023-02-13 at 08 03 47" src="https://user-images.githubusercontent.com/111882034/218403482-a2108350-c0a2-46a8-a79a-6b703858f315.png">
<img width="662" alt="Screenshot 2023-02-13 at 08 03 55" src="https://user-images.githubusercontent.com/111882034/218403489-eb8046f0-0a56-4ccc-a12b-2a52f90ef841.png">

## 🖥 Desktop
 - OS: macOS
 - Browser: Chrome

**Comment by gd2910** [comment] 2023-06-02 08:50
Will be fixed with ticket #474 

Consider code examples to be encapsulated with iframes so that components with ViewBox breakpoints will function as intended.

**Closed by gd2910** 2023-06-02 08:50 UTC
Labels: type: bug 🐛, spike
