### ISSUE TITLE
Update Chip guidance imagery to include Chips V2

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-design-system#236] opened 2023-01-18 12:34 UTC
## What is the purpose of the work?

Need to update guidance imagery on Figma and website to include Chips V2 designs.

## Why do we need it?

Currently imagery on website includes the first rendition of Chip designs, so we need to update the imagery to reflect the changes in design.

**Comment by fbd399** [comment] 2023-01-18 12:37
Images in 'Design System Microsite Assets' Figma file.
Animation videos in Teams folder.

**Comment by DBD324** [comment] 2023-01-26 11:49
Duplicate of #211 and #199. Closing ticket as more detail in 211.

**Closed by DBD324** 2023-01-26 11:49 UTC
