### ISSUE TITLE
[ic-typography]: Update code snippets which include `IcTypography`

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#950] opened 2024-05-09 13:12 UTC
## What component is this related to?

ic-typography

## Why do we need it?

Improve the consistency in code snippets which use IcTypography.
In some snippets, we use IcTypography without any native typography tags (i.e. `p`, `h1`, `h2`, `h3`). It is not clear whether IcTypography will insert the native typography or if this needs to be manually added. 
Example: https://design.sis.gov.uk/components/accordion/code

The guidance mentions IcTypography as a styled wrapper component so there is no need for any guidance updates. 

## Related open issues

N/A

**Comment by GCHQ-Developer-112** [comment] 2024-05-24 08:53
Closing as this is a duplicate of https://github.com/mi6/ic-design-system/issues/927

**Closed by GCHQ-Developer-112** 2024-05-24 08:53 UTC
Labels: guidance
